baseURL = "https://neoisbackagain.github.io/cyber-blog/"
languageCode = 'en-us'
title = 'neoisbackagain'
theme = "PaperMod"
relativeURLs = false                          
canonifyURLs = true                         
[params.assets]
css = ["css/extended/custom.css"]
customJS  = ["js/toc-collapse.js"]



[params]
  defaultTheme = "dark"
  disableThemeToggle = true


[[menu.main]]
  name = "Home"
  url = "/cyber-blog"
  weight = 1

[[menu.main]]
  name = "About Me"
  url = "/cyber-blog/posts/About_Me/"
  weight = 10
