baseURL: "https://neoisbackagain.github.io/cyber-blog/"
title: "My Cyber Blog"
theme: "papermod"
languageCode: "en-us"
paginate: 10

# Keep your contact links
blank_issues_enabled: false
contact_links:
  - name: PaperMod Discussions
    url: https://github.com/adityatelange/hugo-PaperMod/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.

# Recommended for GitHub Pages deployment
relativeURLs: true
canonifyURLs: true
