name: Deploy Hugo site

on:
  push:
    branches:
      - main  # Trigger when you push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Hugo extended (for SCSS/CSS)
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0'
          extended: true

      # Clean old public folder
      - name: Clean public folder
        run: rm -rf public

      # Build Hugo site
      - name: Build Hugo
        run: hugo --minify 

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
        with:
          folder: public
