name: Deploy Hugo site

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setup Hugo
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.117.0'
          extended: true

      # Clean old public folder
      - name: Clean public folder
        run: rm -rf public

      # Build Hugo site
      - name: Build Hugo
        run: hugo --minify

      # Deploy to GitHub Pages
      - uses: actions/deploy-pages@v4
        with:
          folder: public
